Infinite scrolling enhancements and profile button
SubZeroPL/cs-rin-ru-enhanced-mod pull request #27
Opened 2023-07-13 02:28 UTC by Reddiepoint

Cleaned up and simplified the infinite scrolling function and added the profile button next to UCP button.

2023-07-13 06:59 UTC, SubZeroPL commented on cs-rin-ru-enhanced-mod.user.js
> +    if ($(html)[0].src === 'https://cs.rin.ru/forum/styles/rinDark/theme/images/icon_mini_message.gif') {
This will not work on Tor, you should use FORUM_BASE_URL in links

2023-07-13 07:01 UTC, SubZeroPL requested changes
Added some comments

2023-07-14 03:12 UTC, Reddiepoint commented
Sorry for that, I forgot about Tor :(
I've addressed the changes now.

2023-07-14 06:48 UTC, SubZeroPL approved these changes
Looks fine for me

2023-07-16 16:05 UTC, merged