verify if you loged in
SubZeroPL/cs-rin-ru-enhanced-mod pull request #34
Opened 2023-07-18 14:47 UTC by Altansar69

Disables functions that need to be connected

2023-07-19 09:15 UTC, Altansar69 commented
Close #31

2023-07-19 12:37 UTC, SubZeroPL requested changes

2023-07-20 22:34 UTC, Altansar69 commented
I hope it's all good now.

2023-07-21 07:39 UTC, SubZeroPL approved these changes

2023-07-21 15:22 UTC, merged