Improve infinite scrolling and fix bugs
SubZeroPL/cs-rin-ru-enhanced-mod pull request #41
Opened 2023-08-19 07:39 UTC by Reddiepoint

2023-08-21 06:32 UTC, Reddiepoint commented
Added function to partially resolve #28.

2023-08-21 13:02 UTC, Altansar69 commented on cs-rin-ru-enhanced-mod.user.js
> +    while (rgb[0] + rgb[1] + rgb[2] < 350) {
Yes, you're right. You'd have to check the background color and make sure there's enough contrast.

2023-08-22 00:02 UTC, Reddiepoint commented on cs-rin-ru-enhanced-mod.user.js
> +    while (rgb[0] + rgb[1] + rgb[2] < 350) {
I'll have to figure out how to do that unless one of you guys helps me😅

2023-08-22 02:30 UTC, Reddiepoint commented on cs-rin-ru-enhanced-mod.user.js
> +    while (Math.abs(rgb[0] + rgb[1] + rgb[2] - (bgRgb[0] + bgRgb[1] + bgRgb[2])) < 200) {
I haven't decided on what to put for the threshold, right now I have it set to 200. Maybe something higher like 300 would make it look nicer on the light theme.

2023-08-24 11:03 UTC, SubZeroPL requested changes

2023-08-24 11:03 UTC, SubZeroPL commented on cs-rin-ru-enhanced-mod.user.js
> +            const parentElem = titleElem.parentElement
is it needed anywhere else? if not then maybe it would be better to just move it to colorize function

2023-08-24 11:04 UTC, SubZeroPL submitted a review, later dismissed

2023-08-24 13:21 UTC, Reddiepoint commented
Uh oh, I think I did something wrong when I was trying to resolve the merging 😓

2023-09-12 20:03 UTC, SubZeroPL approved these changes

2023-09-13 06:03 UTC, merged